import { Route } from '@angular/router';

export const appRoutes: Route[] = [
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: 'home', loadComponent: () => import('@project-02/views-home').then(m => m.HomeComponent) },
  { path: 'components/autocomplete', loadComponent: () => import('@project-02/views-form-controls').then(m => m.AutocompleteComponent) },
  { path: 'components/checkbox', loadComponent: () => import('@project-02/views-form-controls').then(m => m.CheckboxComponent) },
  { path: 'components/datepicker', loadComponent: () => import('@project-02/views-form-controls').then(m => m.DatepickerComponent) },
  { path: 'components/form-field', loadComponent: () => import('@project-02/views-form-controls').then(m => m.FormFieldComponent) },
  { path: 'components/input', loadComponent: () => import('@project-02/views-form-controls').then(m => m.InputComponent) },
  { path: 'components/radio', loadComponent: () => import('@project-02/views-form-controls').then(m => m.RadioComponent) },
  { path: 'components/select', loadComponent: () => import('@project-02/views-form-controls').then(m => m.SelectComponent) },
  { path: 'components/slide-toggle', loadComponent: () => import('@project-02/views-form-controls').then(m => m.SlideToggleComponent) },
  { path: 'components/menu', loadComponent: () => import('@project-02/views-navigation').then(m => m.MenuComponent) },
  { path: 'components/paginator', loadComponent: () => import('@project-02/views-navigation').then(m => m.PaginatorComponent) },
  { path: 'components/tabs', loadComponent: () => import('@project-02/views-navigation').then(m => m.TabsComponent) },
  { path: 'components/card', loadComponent: () => import('@project-02/views-layout').then(m => m.CardComponent) },
  { path: 'components/divider', loadComponent: () => import('@project-02/views-layout').then(m => m.DividerComponent) },
  { path: 'components/expansion', loadComponent: () => import('@project-02/views-layout').then(m => m.ExpansionComponent) },
  { path: 'components/list', loadComponent: () => import('@project-02/views-layout').then(m => m.ListComponent) },
  { path: 'components/stepper', loadComponent: () => import('@project-02/views-layout').then(m => m.StepperComponent) },
  { path: 'components/badge', loadComponent: () => import('@project-02/views-indicators').then(m => m.BadgeComponent) },
  { path: 'components/button', loadComponent: () => import('@project-02/views-indicators').then(m => m.ButtonComponent) },
  { path: 'components/button-toggle', loadComponent: () => import('@project-02/views-indicators').then(m => m.ButtonToggleComponent) },
  { path: 'components/chips', loadComponent: () => import('@project-02/views-indicators').then(m => m.ChipsComponent) },
  { path: 'components/icon', loadComponent: () => import('@project-02/views-indicators').then(m => m.IconComponent) },
  { path: 'components/progress-bar', loadComponent: () => import('@project-02/views-indicators').then(m => m.ProgressBarComponent) },
  { path: 'components/progress-spinner', loadComponent: () => import('@project-02/views-indicators').then(m => m.ProgressSpinnerComponent) },
  { path: 'components/bottom-sheet', loadComponent: () => import('@project-02/views-overlays').then(m => m.BottomSheetComponent) },
  { path: 'components/dialog', loadComponent: () => import('@project-02/views-overlays').then(m => m.DialogShowcaseComponent) },
  { path: 'components/snack-bar', loadComponent: () => import('@project-02/views-overlays').then(m => m.SnackBarComponent) },
  { path: 'components/tooltip', loadComponent: () => import('@project-02/views-overlays').then(m => m.TooltipComponent) },
  { path: 'components/table', loadComponent: () => import('@project-02/views-table').then(m => m.TableComponent) },
  { path: '**', redirectTo: 'home' },
];
